#!/usr/bin/env python2
import argparse
import logging
import curses
from koditools.remote import Remote

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('--host', dest='host', action='store')
    parser.add_argument('-p', '--port', dest='port', type=int, default=None)
    parser.add_argument('-e', '--event-port', dest='eport', type=int,
                        default=None)
    parser.add_argument('-k', dest='key', action='store', help='Key to send')
    parser.add_argument('-c', '--client', dest='client', action='store_true',
                        default=False)
    parser.add_argument('-v', '--verbose', dest='verbose', action='store_true',
                        default=False)
    args = parser.parse_args()
    logging.root.name = 'kodiremote'
    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)
    r = Remote(args.host, args.port, args.eport)
    if args.client:
        curses.wrapper(r.run)
    elif args.key:
        r.command(args.key)
